// This file is auto-generated by scripts/generate-blogs.mjs
import type { BlogPost } from "./blog-types";

export const blogPosts: BlogPost[] = [
  {
    "slug": "blog",
    "title": "The Art of Slow Mornings",
    "date": "2026-07-10",
    "preview": "There is something quietly radical about refusing to rush. Most mornings, the world asks us to wake up already behind — …",
    "content": "There is something quietly radical about refusing to rush.\n\nMost mornings, the world asks us to wake up already behind — notifications stacked like unpaid bills, calendars dictating the pace before our feet even touch the floor. I used to treat mornings like a sprint: alarm, shower, coffee, laptop, done. Efficient, maybe. But nourishing? Not even close.\n\n## A different ritual\n\nLast month I tried an experiment. No phone for the first forty-five minutes. Just light through the window, the smell of coffee blooming slow in the kitchen, and a notebook that didn't care about deadlines.\n\nThe first week was uncomfortable. My thumb kept reaching for a screen that wasn't there. By the second week, something shifted. Ideas arrived softer. Problems that felt urgent at midnight looked almost funny in the amber hour.\n\n### What I actually do now\n\n1. Wake without checking messages\n2. Drink water before coffee (cliché, but my body stopped arguing)\n3. Write three lines — not goals, just observations\n4. Walk around the block, even when it's raining\n\n> The point isn't productivity. It's presence. A morning that belongs to you, even briefly, changes the texture of everything that follows.\n\n## On building things slowly\n\nI've been building this blog the same way — not as a launch, but as a place to leave small truths. Notes, really. Fragments of what I'm learning about code, design, and the strange joy of making things on the internet.\n\nIf you're reading this, I hope you find a quiet minute today. Make tea. Open a window. Let the day arrive instead of chasing it.\n\nSee you in the next note."
  }
];
