import fs from "fs";
import path from "path";
import matter from "gray-matter";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const blogsDir = path.join(root, "content/blogs");
const outFile = path.join(root, "lib/generated-blogs.ts");

function slugFromFilename(filename) {
  return filename.replace(/\.md$/, "");
}

function buildPreview(content) {
  const plain = content
    .replace(/^#+\s+/gm, "")
    .replace(/[*_`>#-]/g, "")
    .replace(/\s+/g, " ")
    .trim();

  return plain.length > 120 ? `${plain.slice(0, 120)}…` : plain;
}

function parseBlogFile(filename) {
  const slug = slugFromFilename(filename);
  const raw = fs.readFileSync(path.join(blogsDir, filename), "utf8");
  const { data, content } = matter(raw);

  return {
    slug: data.slug ?? slug,
    title: data.title ?? slug,
    date: data.date ?? new Date().toISOString(),
    preview: buildPreview(content),
    content: content.trim(),
  };
}

const posts = fs.existsSync(blogsDir)
  ? fs
      .readdirSync(blogsDir)
      .filter((file) => file.endsWith(".md"))
      .map(parseBlogFile)
      .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
  : [];

const fileContents = `// This file is auto-generated by scripts/generate-blogs.mjs
import type { BlogPost } from "./blog-types";

export const blogPosts: BlogPost[] = ${JSON.stringify(posts, null, 2)};
`;

fs.writeFileSync(outFile, fileContents);
console.log(`Generated ${posts.length} blog post(s) -> lib/generated-blogs.ts`);
